name: PacketHolograms
main: org.hurricanegames.packetholograms.PacketHologramsPlugin
api-version: 1.17
load: STARTUP
depend: [ProtocolSupport, ProtocolLib]
softdepend: [PlaceholderAPI]
version: ${version}

commands:
  holograms:
    description: All PacketHolograms commands
    aliases:
    - hologram
    - holo
    usage: '/holo'

author: _Shevchik_
