name: PacketHolograms
main: org.hurricanegames.packetholograms.PacketHologramsPlugin
version: 1.0
api-version: 1.15
author: _Shevchik_
load: STARTUP
depend: [ProtocolSupport, ProtocolLib]
softdepend: [PlaceholderAPI]
commands:
  holograms:
    description: All PacketHolograms commands
    aliases:
    - hologram
    - holo
    usage: '/holo'
